### ISSUE TITLE
Font MIME type with the RFC 8081

### ISSUE THREAD

**Issue by LeoColomb** [h5bp/server-configs#177]
Hi @h5bp/server-configs folks!

Recent changes introduced by the [RFC 8081](https://tools.ietf.org/html/rfc8081) and [registered at IANA](https://www.iana.org/assignments/media-types/media-types.xml#font) about font media types should be applied to server configs, shouldn't it?

Current|New
---|---
`application/x-font-ttf`|`font/ttf`
`application/font-otf` or `font/opentype`|`font/otf`
`application/font-woff`|`font/woff`
`application/font-woff2`|`font/woff2`
`application/font-cff` or `application/x-font-ttf` (.ttc)|`font/collection`

---

* [x] Apache: https://github.com/h5bp/server-configs-apache/pull/114
* [x] Nginx: https://github.com/h5bp/server-configs-nginx/pull/187
* [ ] Internet Information Services (IIS) (?)
* [x] lighttpd (out of maintenance)

**Comment by LeoColomb** [comment]
Ping @alrra just in case ! 😇

**Comment by ChrisMcKee** [comment]
Woff/Woff2 are already in there as are TTF/OTF... sfnt is the basis of woff / otf / ot; are cff/sfnt currently in use anywhere (webfont wise)?


https://www.iana.org/assignments/media-types/application/font-sfnt
https://blog.typekit.com/2010/12/02/the-benefits-of-opentypecff-over-truetype/

**Comment by LeoColomb** [comment]
> Woff/Woff2 are already in there as are TTF/OTF... sfnt is the basis of woff / otf / ot;

What do you mean?

**Comment by ChrisMcKee** [comment]
woff/2/ttf/otf mime types are already in the configs.
Are CFF/SFNT in use on the web at the moment?

**Comment by LeoColomb** [comment]
> woff/2/ttf/otf mime types are already in the configs.

Yep, but my issue points out that there is an update regarding the media types of these file types.
This update is introduced by the RFC 8081 published on February 2017.

> Are CFF/SFNT in use on the web at the moment?

May be not... 😄
